-- Script de configuración para sistema de atención médica veterinaria
-- Oracle Autonomous Database 19c

-- Eliminar secuencias si existen (para reinicios)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PACIENTE_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CONSULTA_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ATENCION_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Eliminar tablas si existen (para reinicios)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ATENCIONES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONSULTAS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PACIENTES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Crear secuencias para IDs
CREATE SEQUENCE PACIENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE CONSULTA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE ATENCION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Crear tabla de pacientes
CREATE TABLE PACIENTES (
    ID NUMBER(10) PRIMARY KEY,
    RUT VARCHAR2(12) UNIQUE NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(150),
    DIRECCION VARCHAR2(255),
    SEXO VARCHAR2(1),
    ESTADO_CIVIL VARCHAR2(20)
);

-- Crear tabla de consultas
CREATE TABLE CONSULTAS (
    ID NUMBER(10) PRIMARY KEY,
    PACIENTE_ID NUMBER(10) NOT NULL,
    FECHA_CONSULTA TIMESTAMP NOT NULL,
    MOTIVO_CONSULTA CLOB,
    SINTOMAS CLOB,
    DIAGNOSTICO CLOB,
    TRATAMIENTO CLOB,
    OBSERVACIONES CLOB,
    MEDICO VARCHAR2(100),
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES(ID)
);

-- Crear tabla de atenciones
CREATE TABLE ATENCIONES (
    ID NUMBER(10) PRIMARY KEY,
    CONSULTA_ID NUMBER(10) NOT NULL,
    PACIENTE_ID NUMBER(10) NOT NULL,
    FECHA_ATENCION TIMESTAMP NOT NULL,
    TIPO_ATENCION VARCHAR2(100),
    ESPECIALIDAD VARCHAR2(100),
    RESULTADO CLOB,
    PRESCRIPCIONES CLOB,
    PROXIMA_CITA VARCHAR2(200),
    ESTADO VARCHAR2(50),
    CONSTRAINT FK_ATENCION_CONSULTA FOREIGN KEY (CONSULTA_ID) REFERENCES CONSULTAS(ID),
    CONSTRAINT FK_ATENCION_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES(ID)
);

-- Insertar datos de prueba
-- Pacientes
INSERT INTO PACIENTES (ID, RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION, SEXO, ESTADO_CIVIL) VALUES 
(PACIENTE_SEQ.NEXTVAL, '12345678-9', 'Juan', 'Pérez', TO_DATE('1985-05-15', 'YYYY-MM-DD'), '+56912345678', 'juan.perez@email.com', 'Av. Principal 123', 'M', 'Soltero');

INSERT INTO PACIENTES (ID, RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION, SEXO, ESTADO_CIVIL) VALUES 
(PACIENTE_SEQ.NEXTVAL, '98765432-1', 'María', 'González', TO_DATE('1992-08-22', 'YYYY-MM-DD'), '+56987654321', 'maria.gonzalez@email.com', 'Calle Secundaria 456', 'F', 'Casada');

INSERT INTO PACIENTES (ID, RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION, SEXO, ESTADO_CIVIL) VALUES 
(PACIENTE_SEQ.NEXTVAL, '11111111-1', 'Carlos', 'Rodríguez', TO_DATE('1978-12-03', 'YYYY-MM-DD'), '+56911111111', 'carlos.rodriguez@email.com', 'Pasaje Los Robles 789', 'M', 'Divorciado');

INSERT INTO PACIENTES (ID, RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION, SEXO, ESTADO_CIVIL) VALUES 
(PACIENTE_SEQ.NEXTVAL, '22222222-2', 'Ana', 'Martínez', TO_DATE('1995-03-18', 'YYYY-MM-DD'), '+56922222222', 'ana.martinez@email.com', 'Plaza Central 321', 'F', 'Soltera');

INSERT INTO PACIENTES (ID, RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION, SEXO, ESTADO_CIVIL) VALUES 
(PACIENTE_SEQ.NEXTVAL, '33333333-3', 'Pedro', 'Silva', TO_DATE('1980-07-10', 'YYYY-MM-DD'), '+56933333333', 'pedro.silva@email.com', 'Boulevard Norte 654', 'M', 'Casado');

-- Consultas
INSERT INTO CONSULTAS (ID, PACIENTE_ID, FECHA_CONSULTA, MOTIVO_CONSULTA, SINTOMAS, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES, MEDICO) VALUES 
(CONSULTA_SEQ.NEXTVAL, 1, TO_TIMESTAMP('2025-08-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Dolor de cabeza constante', 'Cefalea, mareos, náuseas', 'Migraña tensional', 'Analgésicos y relajantes musculares', 'Reducir estrés, buena hidratación', 'Dr. Fernández');

INSERT INTO CONSULTAS (ID, PACIENTE_ID, FECHA_CONSULTA, MOTIVO_CONSULTA, SINTOMAS, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES, MEDICO) VALUES 
(CONSULTA_SEQ.NEXTVAL, 2, TO_TIMESTAMP('2025-08-16 14:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Control embarazo', 'Náuseas matutinas, fatiga', 'Embarazo de 12 semanas normal', 'Vitaminas prenatales', 'Control mensual, dieta equilibrada', 'Dra. López');

INSERT INTO CONSULTAS (ID, PACIENTE_ID, FECHA_CONSULTA, MOTIVO_CONSULTA, SINTOMAS, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES, MEDICO) VALUES 
(CONSULTA_SEQ.NEXTVAL, 3, TO_TIMESTAMP('2025-08-17 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Dolor en el pecho', 'Dolor torácico, dificultad respiratoria', 'Ansiedad generalizada', 'Ansiolíticos suaves', 'Terapia psicológica recomendada', 'Dr. Morales');

INSERT INTO CONSULTAS (ID, PACIENTE_ID, FECHA_CONSULTA, MOTIVO_CONSULTA, SINTOMAS, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES, MEDICO) VALUES 
(CONSULTA_SEQ.NEXTVAL, 1, TO_TIMESTAMP('2025-08-20 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Seguimiento migraña', 'Mejora del dolor de cabeza', 'Evolución favorable de migraña', 'Continuar tratamiento', 'Control en 2 semanas', 'Dr. Fernández');

INSERT INTO CONSULTAS (ID, PACIENTE_ID, FECHA_CONSULTA, MOTIVO_CONSULTA, SINTOMAS, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES, MEDICO) VALUES 
(CONSULTA_SEQ.NEXTVAL, 4, TO_TIMESTAMP('2025-08-22 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Examen preventivo', 'Asintomática', 'Estado de salud normal', 'Mantener estilo de vida saludable', 'Control anual', 'Dra. Castro');

-- Atenciones
INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 1, 1, TO_TIMESTAMP('2025-08-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Consulta médica', 'Neurología', 'Tratamiento iniciado exitosamente', 'Ibuprofeno 400mg cada 8 horas por 5 días', '2025-09-15', 'Completada');

INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 2, 2, TO_TIMESTAMP('2025-08-16 14:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Control prenatal', 'Ginecología', 'Embarazo evolucionando normalmente', 'Ácido fólico 5mg diarios', '2025-09-16', 'Completada');

INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 3, 3, TO_TIMESTAMP('2025-08-17 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Evaluación cardiológica', 'Cardiología', 'Exámenes cardiológicos normales', 'Alprazolam 0.5mg según necesidad', '2025-09-17', 'Completada');

INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 4, 1, TO_TIMESTAMP('2025-08-20 17:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Seguimiento neurológico', 'Neurología', 'Paciente en mejora progresiva', 'Reducir dosis de analgésicos', '2025-09-05', 'En proceso');

INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 5, 4, TO_TIMESTAMP('2025-08-22 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chequeo preventivo', 'Medicina General', 'Exámenes de laboratorio normales', 'Multivitamínicos diarios', '2026-08-22', 'Completada');

INSERT INTO ATENCIONES (ID, CONSULTA_ID, PACIENTE_ID, FECHA_ATENCION, TIPO_ATENCION, ESPECIALIDAD, RESULTADO, PRESCRIPCIONES, PROXIMA_CITA, ESTADO) VALUES 
(ATENCION_SEQ.NEXTVAL, 1, 1, TO_TIMESTAMP('2025-08-25 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Terapia física', 'Kinesiología', 'Inicio de terapia para migraña tensional', 'Ejercicios de relajación cervical', '2025-09-01', 'Programada');

COMMIT;
